/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTorrentsIndexRouteImport } from './routes/api/torrents/index'
import { Route as ApiTorrentsEventsRouteImport } from './routes/api/torrents/events'
import { Route as ApiTorrentsControlRouteImport } from './routes/api/torrents/control'
import { Route as ApiAuthSettingsRouteImport } from './routes/api/auth/settings'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiTorrentsIdIndexRouteImport } from './routes/api/torrents/$id/index'
import { Route as ApiTorrentsIdStreamRouteImport } from './routes/api/torrents/$id/stream'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorrentsIndexRoute = ApiTorrentsIndexRouteImport.update({
  id: '/api/torrents/',
  path: '/api/torrents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorrentsEventsRoute = ApiTorrentsEventsRouteImport.update({
  id: '/api/torrents/events',
  path: '/api/torrents/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorrentsControlRoute = ApiTorrentsControlRouteImport.update({
  id: '/api/torrents/control',
  path: '/api/torrents/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSettingsRoute = ApiAuthSettingsRouteImport.update({
  id: '/api/auth/settings',
  path: '/api/auth/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorrentsIdIndexRoute = ApiTorrentsIdIndexRouteImport.update({
  id: '/api/torrents/$id/',
  path: '/api/torrents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTorrentsIdStreamRoute = ApiTorrentsIdStreamRouteImport.update({
  id: '/api/torrents/$id/stream',
  path: '/api/torrents/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/torrents/control': typeof ApiTorrentsControlRoute
  '/api/torrents/events': typeof ApiTorrentsEventsRoute
  '/api/torrents/': typeof ApiTorrentsIndexRoute
  '/api/torrents/$id/stream': typeof ApiTorrentsIdStreamRoute
  '/api/torrents/$id/': typeof ApiTorrentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/torrents/control': typeof ApiTorrentsControlRoute
  '/api/torrents/events': typeof ApiTorrentsEventsRoute
  '/api/torrents': typeof ApiTorrentsIndexRoute
  '/api/torrents/$id/stream': typeof ApiTorrentsIdStreamRoute
  '/api/torrents/$id': typeof ApiTorrentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/settings': typeof ApiAuthSettingsRoute
  '/api/torrents/control': typeof ApiTorrentsControlRoute
  '/api/torrents/events': typeof ApiTorrentsEventsRoute
  '/api/torrents/': typeof ApiTorrentsIndexRoute
  '/api/torrents/$id/stream': typeof ApiTorrentsIdStreamRoute
  '/api/torrents/$id/': typeof ApiTorrentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/settings'
    | '/api/torrents/control'
    | '/api/torrents/events'
    | '/api/torrents/'
    | '/api/torrents/$id/stream'
    | '/api/torrents/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manage'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/settings'
    | '/api/torrents/control'
    | '/api/torrents/events'
    | '/api/torrents'
    | '/api/torrents/$id/stream'
    | '/api/torrents/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/manage'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/settings'
    | '/api/torrents/control'
    | '/api/torrents/events'
    | '/api/torrents/'
    | '/api/torrents/$id/stream'
    | '/api/torrents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManageRoute: typeof ManageRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSettingsRoute: typeof ApiAuthSettingsRoute
  ApiTorrentsControlRoute: typeof ApiTorrentsControlRoute
  ApiTorrentsEventsRoute: typeof ApiTorrentsEventsRoute
  ApiTorrentsIndexRoute: typeof ApiTorrentsIndexRoute
  ApiTorrentsIdStreamRoute: typeof ApiTorrentsIdStreamRoute
  ApiTorrentsIdIndexRoute: typeof ApiTorrentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torrents/': {
      id: '/api/torrents/'
      path: '/api/torrents'
      fullPath: '/api/torrents/'
      preLoaderRoute: typeof ApiTorrentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torrents/events': {
      id: '/api/torrents/events'
      path: '/api/torrents/events'
      fullPath: '/api/torrents/events'
      preLoaderRoute: typeof ApiTorrentsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torrents/control': {
      id: '/api/torrents/control'
      path: '/api/torrents/control'
      fullPath: '/api/torrents/control'
      preLoaderRoute: typeof ApiTorrentsControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/settings': {
      id: '/api/auth/settings'
      path: '/api/auth/settings'
      fullPath: '/api/auth/settings'
      preLoaderRoute: typeof ApiAuthSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torrents/$id/': {
      id: '/api/torrents/$id/'
      path: '/api/torrents/$id'
      fullPath: '/api/torrents/$id/'
      preLoaderRoute: typeof ApiTorrentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/torrents/$id/stream': {
      id: '/api/torrents/$id/stream'
      path: '/api/torrents/$id/stream'
      fullPath: '/api/torrents/$id/stream'
      preLoaderRoute: typeof ApiTorrentsIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManageRoute: ManageRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSettingsRoute: ApiAuthSettingsRoute,
  ApiTorrentsControlRoute: ApiTorrentsControlRoute,
  ApiTorrentsEventsRoute: ApiTorrentsEventsRoute,
  ApiTorrentsIndexRoute: ApiTorrentsIndexRoute,
  ApiTorrentsIdStreamRoute: ApiTorrentsIdStreamRoute,
  ApiTorrentsIdIndexRoute: ApiTorrentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
